### ISSUE TITLE
_AudioPlayerPageState Memory Leak

### ISSUE THREAD

**Issue by minikin** [HighVibe/hvn#130]
We have a memory leak in _AudioPlayerPageState.
I believe that because of the way we handle state management and dependencies injections.

<details><summary>Logs</summary>
<p>

```sh
flutter: -- AudioModule DISPOSED
flutter: -- OtherUserModule DISPOSED
flutter: -- ProfileModule DISPOSED
flutter: Match! Processing /profile/user/9XcZVEB1BUX8zKuTqkMH as /profile/user/:userId
flutter: Result processed /profile/user/9XcZVEB1BUX8zKuTqkMH as /profile/user/9XcZVEB1BUX8zKuTqkMH
flutter: -- ProfileModule INITIALIZED
flutter: -- OtherUserModule INITIALIZED
flutter: -- AudioModule INITIALIZED
flutter: -- AudioPlayerModule INITIALIZED
flutter: -- AudioPlayerModule DISPOSED
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): _AudioPlayerPageState#bf91f(lifecycle state: defunct, not mounted, tickers: tracking 0 tickers)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> <…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add  (dart:async/broadcast_stream_controller.dart:251:24)
#1      AudioPlayer._doHandlePlatformCall
package:audioplayers/audioplayers.dart:575
#2      AudioPlayer.platformCallHandler
package:audioplayers/audioplayers.dart:538
#3      MethodChannel._handleAsMethodCall
package:flutter/…/services/platform_channel.dart:409
#4      MethodChannel.setMethodCallHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:377
#5      _DefaultBinaryMessenger.handlePlatformMessage
package:flutter/…/services/binding.dart:199
#6      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:290:15)
#7      _rootRun  (dart:async/zone.dart:1184:13)
#8      _CustomZone.run  (dart:async/zone.dart:1077:19)
#9      _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
#10     _invoke3  (dart:ui/hooks.dart:289:10)


This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> <…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add  (dart:async/broadcast_stream_controller.dart:251:24)
#1      AudioPlayer._doHandlePlatformCall
package:audioplayers/audioplayers.dart:575
#2      AudioPlayer.platformCallHandler
package:audioplayers/audioplayers.dart:538
#3      MethodChannel._handleAsMethodCall
package:flutter/…/services/platform_channel.dart:409
#4      MethodChannel.setMethodCallHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:377
#5      _DefaultBinaryMessenger.handlePlatformMessage
package:flutter/…/services/binding.dart:199
#6      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:290:15)
#7      _rootRun  (dart:async/zone.dart:1184:13)
#8      _CustomZone.run  (dart:async/zone.dart:1077:19)
#9      _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
#10     _invoke3  (dart:ui/hooks.dart:289:10)
#11     _dispatchPlatformMessage (d<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add  (dart:async/broadcast_stream_controller.dart:251:24)
#1      AudioPlayer._doHandlePlatformCall
package:audioplayers/audioplayers.dart:575
#2      AudioPlayer.platformCallHandler
package:audioplayers/audioplayers.dart:538
#3      MethodChannel._handleAsMethodCall
package:flutter/…/services/platform_channel.dart:409
#4      MethodChannel.setMethodCallHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:377
#5      _DefaultBinaryMessenger.handlePlatformMessage
package:flutter/…/services/binding.dart:199
#6      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:290:15)
#7      _rootRun  (dart:async/zone.dart:1184:13)
#8      _CustomZone.run  (dart:async/zone.dart:1077:19)
#9      _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
#10     _invoke3  (dart:ui/hooks.dart:289:10)
#11     _dispatchPlatformMessage (d<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add  (dart:async/broadcast_stream_controller.dart:251:24)
#1      AudioPlayer._doHandlePlatformCall
package:audioplayers/audioplayers.dart:586
#2      AudioPlayer.platformCallHandler
package:audioplayers/audioplayers.dart:538
#3      MethodChannel._handleAsMethodCall
package:flutter/…/services/platform_channel.dart:409
#4      MethodChannel.setMethodCallHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:377
#5      _DefaultBinaryMessenger.handlePlatformMessage
package:flutter/…/services/binding.dart:199
#6      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:290:15)
#7      _rootRun  (dart:async/zone.dart:1184:13)
#8      _CustomZone.run  (dart:async/zone.dart:1077:19)
#9      _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
#10     _invoke3  (dart:ui/hooks.dart:289:10)
#11     _dispatchPlatformMessage (d<…>
```
</details>

**To Reproduce**
1. Start app
2. GO to 'Jason Doh' profile
3. Play 'Autumn Sunset' and minimize Audio Player
4. Return to 'Home' '
5. GO to 'Jason Doh' profile
6. Play 'Clouds' tune

**Expected behavior**
No memory leaks.

**OS:**
 - iOS/Android

**Smartphone:**
- Real devices and simulators/emulators

**Comment by 7flash** [comment]
I believe it's solved by #128 let me know if it appears again
